### ISSUE TITLE
BacktraderPlottingOpBrowser() doesn't work in demo

### ISSUE THREAD

**Issue by Jake0303** [happydasch/btplotting#16]
@happydasch 

I tried the optimization sample file in : https://github.com/happydasch/btplotting/blob/master/demos/optimization.py and it doesn't work. I get error, **There is no current event loop in thread.** See below images on error message.

![image](https://user-images.githubusercontent.com/5394743/125817620-a576d645-8548-4054-872e-fb361e7856ea.png)

![image](https://user-images.githubusercontent.com/5394743/125817657-c7b51c92-bd45-4207-b653-7fe0f3e8a6d9.png)

**Comment by happydasch** [comment]
I am not really sure about the error you get, but i updated the example to support optimize. Reopen if that  is still a issue for you.

**Comment by happydasch** [comment]
Also i am working atm on some updates for optimize to support genetic optimization. so after this it should fully work. but the whole code is a work in progress, so feel free to report any issues you encounter.

**Comment by Jake0303** [comment]
> Also i am working atm on some updates for optimize to support genetic optimization. so after this it should fully work. but the whole code is a work in progress, so feel free to report any issues you encounter.

Awesome, actually so am I. An AI Strategy generator that uses genetic optimization to produce multiple strategies with a date range. I will retry with the update example

**Comment by ReyWalter** [comment]
Hi there, I'm also working on the same project as Jake. I'm his junior developer. We implemented our project in Flask. I'm having an issue where I can't see the result by using `browser.start()` and when I try to access it manually by putting localhost:80 in the url, it gives me an error "There is no current event loop in the thread 'Thread-12'". Our project is using localhost:5000 while the `browser.start()` is using localhost:80. The code for plotting works if Flask is not used, basically, just pure Python. Is there anyway we could get the result other than accessing localhost:80? Like put the result in html file so that we don't have to access the page with different server port?
![screenshot](https://user-images.githubusercontent.com/84330918/126017817-5b6ee330-f365-4341-bce1-b0cd693cb3b7.PNG)
![image](https://user-images.githubusercontent.com/84330918/126017828-71649013-802c-4518-977d-d6b9fb36cf65.png)

**Comment by happydasch** [comment]
you can set the port for the live client and opt browser.

for opt browser:

```
    btp = BacktraderPlotting()
    browser = BacktraderPlottingOptBrowser(btp, result, port=5000)
    browser.start()
```

for live plotting:

```
cerebro.addanalyzer(
            BacktraderPlottingLive,
            port=5000)
```

**Comment by ReyWalter** [comment]
Hey there, I tried changing the port but it didn't fix the error. I think because our main page is runned by Flask in localhost:5000 and the `browser.start()` is runned by Backtrader in the same url, it causes a conflict in the server. I have a solution for this but I need your advice or recommendation before I start implement it. Also, correct me if I'm wrong. So my solution is to run the `browser.start()` in a different url, for example, localhost:5000/resultPage. My question tho is if it's possible. If it is, how do I change the url to show the result?

**Comment by happydasch** [comment]
you are getting a status code 500 page back. so there is an issue with the strategy itself (maybe you do not add data for example). from the errors posted i cannot say much about the issue you have. but for the integration with flask, you may check out 

https://github.com/happydasch/btplotting/blob/master/btplotting/webapp.py

and

https://github.com/happydasch/btplotting/blob/master/btplotting/optbrowser.py

on how to integrate btplotting in a flask server architecture.
