### ISSUE TITLE
Replacing Bokeh with `pyecharts` for better performance

### ISSUE THREAD

**Issue by ittianyu** [happydasch/btplotting#39]
#### Reason
Web pages are very slow when zooming with long bars (greater than 3000).

I use `pyecharts` to draw the same bars,  it's smooth.

#### Thanks
I would like to implement it, but I don't understand how it works yet.

Finally, thank you for your selfless dedication. Hope to hear from you.

**Comment by happydasch** [comment]
you may want to check out using webgl rendering for output, try also if canvas changes anything for speed. 

https://github.com/happydasch/btplotting/blob/0f3a855317708e72e5855c4c2b9322fc79720541/btplotting/schemes/scheme.py#L230


for pyecharts, this lib would not be possible to replace bokeh, since it is being used for the whole html generation. the only replacement that comes in my mind would be plotly.
